# Generated by Django 4.1.5 on 2023-01-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0002_normaluser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='username',
        ),
    ]
