# Generated by Django 4.1.5 on 2023-01-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0003_remove_normaluser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
    ]
