# Generated by Django 4.1.5 on 2023-01-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0004_remove_userprofile_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
