# Generated by Django 4.1.5 on 2023-01-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0005_alter_userprofile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, default='base_app/static/img/avatar/blank_profile.png', upload_to='profile'),
        ),
    ]
