# Generated by Django 4.1.5 on 2023-01-03 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('1', 'Open'), ('2', 'Completed'), ('3', 'Completed')], default=1, max_length=7)),
                ('is_active', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default=1, max_length=7)),
                ('expected_start_date', models.DateField(auto_now_add=True)),
                ('expected_end_date', models.DateField()),
                ('Priority', models.CharField(choices=[('1', 'Medium'), ('2', 'Low'), ('3', 'High')], default=1, max_length=7)),
                ('description', models.TextField(blank=True)),
                ('assign', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
