# Generated by Django 4.1.5 on 2023-01-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assign',
        ),
    ]
