# Generated by Django 4.1.5 on 2023-01-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Priority',
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default=1, max_length=17),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Completed'), ('3', 'Completed')], default=1, max_length=15),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('1', 'Medium'), ('2', 'Low'), ('3', 'High')], default=1, max_length=15),
        ),
    ]
