# Generated by Django 4.1.5 on 2023-01-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0002_remove_project_priority_alter_project_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
