# Generated by Django 4.1.5 on 2023-01-20 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0003_project_created_by_alter_project_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='expected_end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='expected_start_date',
        ),
    ]
