# Generated by Django 4.1.5 on 2023-01-22 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management_app', '0003_remove_task_user_alter_task_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('1', 'internal'), ('2', 'external')], default=1, max_length=15),
        ),
    ]
