# Generated by Django 4.1.5 on 2023-01-22 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0001_initial'),
        ('project_management_app', '0005_alter_task_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register_app.normaluser'),
        ),
    ]
