# Generated by Django 4.1.5 on 2023-01-03 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management_app', '0005_remove_project_assign_project_assign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('1', 'Open'), ('2', 'Completed'), ('3', 'Completed')], default=1, max_length=15)),
                ('type', models.CharField(choices=[('1', 'internal'), ('2', 'external')], max_length=15)),
                ('priority', models.CharField(choices=[('1', 'Medium'), ('2', 'Low'), ('3', 'High')], default=1, max_length=15)),
                ('expected_start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('assign', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management_app.project')),
            ],
            options={
                'ordering': ['project', 'task_name'],
            },
        ),
    ]
