# Generated by Django 4.1.5 on 2023-01-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0006_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Completed'), ('3', 'Cancelled')], default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Completed'), ('3', 'Cancelled')], default=1, max_length=15),
        ),
    ]
